### ISSUE TITLE
I see something tasty brewing here!

### ISSUE THREAD

**Issue by bartekus** [opencredo/opencredo-react-boilerplate#17]
How could I be of an assistance gentlemen?

**Comment by bartekus** [comment]
FYI currently absence of 'app-config' along with lack of an example of one, makes the build unusable to the majority of the community.
I presume this to be temporary and intentional but I though I'll report it none the less.

**Comment by mcalthrop** [comment]
Hey @Bartekus 

Thanks so much for dropping by and taking the time to comment. Glad you see something brewing!

As you can see, we've not long ago started the project, and are grateful for offers of help & feedback... I'll get back to you as soon as I can (near end of day here :smiley:).

Matt

**Comment by mcalthrop** [comment]
And yes, the lack of a `src/app-config.js` file is an oversight... will rectify. :+1:

**Comment by bartekus** [comment]
Howdy @mcalthrop 

And not just something, I'm primarily attracted by the quality and diligence in the source code and looks very yum so I'd like to spread the good news about it.

As a side note, being I'm somewhat impatient I've located an example config on the feature/9-flowtype branch on your colleagues account :) so I'm already there, I really like it I must say, I'll be monitoring this and help out in any capacity that I can!

**Comment by mcalthrop** [comment]
Fantastic to hear! Well done for finding the sample... I'm just on it now. Couldn't go to bed without fixing it. :neckbeard:

**Comment by bartekus** [comment]
Perhaps I'll start writing a introductory article/general-how-to on Medium so that once you guys are ready to launch, I'll have you review it, then I'll post it and we'll put the whole project in overdrive :D

I'm particularly looking at surpassing the current champion, react-starter-kit, as it's rather poor learning material for new react users, being that they do not follow standards outlined by the community while you guys are bang on/spot on.

**Comment by mcalthrop** [comment]
There are definitely lots of voices out there, so it's nice to hear from someone who sees things in a similar way. Now to convince the rest of the world, hey? :wink:

**Comment by mcalthrop** [comment]
btw, I also just published a blog post on the OpenCredo website that you might be interested in:

https://twitter.com/OpenCredo/status/687974805686075393

As before, comments & feedback welcome.

**Comment by bartekus** [comment]
That won't be a problem, I assure you. 
When the quality speaks for itself, all man has to do is point to the truth contained with in. :D

I'll be using your final product to build a framework (R3Stack, based on the concepts that we're outlined in the 3ree stack by Gordon Dent) and further expanded by the meatier stack build on meteor concept. I'm intending to simplify it by using of deepstream.io vs socketcluster

**Comment by mcalthrop** [comment]
@Bartekus: have fixed the bug, and merged back into `master`.

Could you verify please?

**Comment by bartekus** [comment]
my git pull resulted in:

```
Fast-forward
 .gitignore        | 1 -
 src/app-config.js | 4 ++++
 src/index.html    | 2 +-
 3 files changed, 5 insertions(+), 2 deletions(-)
```

subsequent npm start resulted in smooth startup!

The issue has been verified to be corrected and the entire build is now fully operational!
Awesome Job guys!

**Comment by mcalthrop** [comment]
Great to hear Bartek, and thanks for checking. It's great to have a second/third set of eyes.

If it's ok with you, I'll close this issue so that we can keep its focus primarily to the bug.

Feel free to raise another issue if you see something you want to know more about, comment on, feed back, etc.

**Comment by mcalthrop** [comment]
Oh, I just saw that you closed it already! Cool.
