### ISSUE TITLE
Add "Features" section to README

### ISSUE THREAD

**Issue by mcalthrop** [opencredo/opencredo-react-boilerplate#24]
Add a **Features** section to the `README` that details some of the main features of this project.

For example:
- [x] ES6/7
- [x] Flowtype
- [x] Redux
- [x] react-router
- [x] webpack
- [x] Bootstrap
- [x] SCSS
- [x] foundation for [protected pages](https://github.com/opencredo/opencredo-react-boilerplate/pull/20)
- [x] react-intl

**Comment by vincemtnz** [comment]
Other things to add tot he features list:
- [x] [react-intl v2](https://github.com/yahoo/react-intl/issues/162) for i18n and location of translations.
