### ISSUE TITLE
Add a "Structure" section to the README

### ISSUE THREAD

**Issue by vincemtnz** [opencredo/opencredo-react-boilerplate#26]
There are a few conventions in place in this boilerplate that might not seem evident on first sight. Having a short graph detailing the project's structure will help in this regard. 

For example, the components vs containers convention is extended here with the `src/pages/` directory (which holds components that live in routes).

I'll add this hopefully today so I'm creating this issue to track it.

**Comment by mcalthrop** [comment]
:+1:
