### ISSUE TITLE
Preliminary inquiry...

### ISSUE THREAD

**Issue by bartekus** [opencredo/opencredo-react-boilerplate#30]
Hello Gentlemen, 
   I've got a proposition that I'd like you and your colleagues to consider as I'd like you all on board of a new open software initiative:
Under Araphel.org, an esoteric conclave would be established to oversight an OSI project called R3Stack (R3Stack.com is the stacks url)

Our main component is currently being finalized by Matt Krick with his Meatier development. 
Basically it's a meteor-like stack build within react-redux-rethinkDB specifications, you can check it out here: https://github.com/mattkrick/meatier

Your beautiful creation would be the frontend (replacing the current meatier mui) as I have not see anything better or eloquent if I may say so, that I'd love kids to learn on, but we'll get to that in a moment.

Finally we are in preliminary talks with Alex Pustovalov of the Structor project which we hope to include too as an visual aspect to an concise functional programming is an great aid in teaching children while itself not obstructing or weighing in too much in unnecessary code; you can see here: https://github.com/ipselon/structor

The whole thing will either be entirely docker based as to simplify the installation/operation/deployment or we could utilize AZK as binding agent/control agent (tho since itself is also docker base it could be entirely unnecessary, however all this is open to discussion)

The reason for this stack, is to create a framework which unlike other frameworks, do not lend itself to be ridged and unchanging but rather continually evolve with community while providing kids with the best practice, that are always current and reflective of the react community; an full-spectrum solution with emphasis on functional programming that ever-improving.

Our aim would be to providing the best structure for learning by allowing kids to look at the current development practices, while at the same time having entire build for reverse engineering purposes as it is my belief that by such example the widest segment of differentiating potential that kids have could be sparked and nurtured.

By setting an ever evolving standard we can bring balance to the fractured and disjoined react [force ;) ] community and at the same time support the good practices while discarding unwanted ones.

The structure of Araphel.org in a way like that of a philosophical branch of the anonymous movement and itself will be in form of a round table, where each member does his best to express and contribute in whatever capacity they can while at the same time setting an example and nurturing community in general. We will essentially create by hackers for hacker - build-break-learn stack.

What would you say to that?

**Comment by mcalthrop** [comment]
Hi @Bartekus

We appreciate your sharing your thoughts.

At this early stage, our focus is to provide a simple foundation for building a React application.

This has been motivated by our experience on recent projects, and we would like to make it available for others in a similar situation.

So we are keeping the scope minimal so that we can release a stable baseline within a reasonable timeframe.

**Comment by bartekus** [comment]
That's absolutely fine @mcalthrop, I think you guys are doing incredible job and I for one can't simply thank you guys enough!
So while the direct involvement with the r3stack project is not currently possible for you guys I would still like to get a proverbial blessings and a 'ok, go ahead' in terms of drafting your undertaking into the general scope of the r3stack project. This will not cause or require any additional effort beyond the one that you have set for yourself and are currently undertaking. Since as I've explained the goal of our r3stack effort is to bring an exposer to proper procedures and techniques that are relevant to the react community and reflective of its nature. As a gathering of like-minded professionals who would like to combine best techniques and solutions into one 'framework' like entity for the purpose of ongoing showcase that facilitates learning thru concept-exposure and back-engineering. 
So in conclusion, we do not require your direct participation but would like to use your marvelous creation as the front-end for r3stack, as we have not been able to find anything even closely matching the superb quality that opencredo-react-boilerplate is build upon. In turn, your work will gain a lot more exposer and thru it so will all of you as well. 
Hard work thru excellence creates supreme results, which deserves to be recognized, praised and showcase; by teaching new generation of future developers the best of what we can do, in turn we teach them to be the best that they can be and continue this process onwards.

So once again, I deeply and sincerely thank you for all your hard work and dedication and hope that you will not mind us using your work as tool to teach what we believe web development should be all about.

**Comment by mcalthrop** [comment]
Hi @Bartekus 

Sorry for the late reply!

The project is open-sourced with the [MIT License](https://github.com/opencredo/opencredo-react-boilerplate/blob/master/LICENSE), so as long as you follow the guidelines therein, you'll be fine. :-)

Matt

**Comment by bartekus** [comment]
Hello @mcalthrop 

Indeed, but I like to ask for permission regardless, it just feels better and obviously credit is always given where it's due! 

Sincerely,
Bart

**Comment by mcalthrop** [comment]
Much appreciated! :-)
