### ISSUE TITLE
Adding BrowserSync: Partial success

### ISSUE THREAD

**Issue by bartekus** [opencredo/opencredo-react-boilerplate#41]
So I've had a crazy idea and wanted to add BrowserSync to your perfect boilerplate, here is what I've done:

```
const yargs = require('yargs');
const browserSync = require('browser-sync');
const express = require('express');
const webpack = require('webpack');
const debug = require('debug');
const config = require('../config');
const history = require('connect-history-api-fallback');
const webpackconfig = require('../webpack.config');
const webpackDevMiddleware = require('webpack-dev-middleware');
const webpackHotMiddleware = require('webpack-hot-middleware');

debug.enable('app:*');

const app = express();
const compiler = webpack(webpackconfig);

const log = debug('app:server');

log('Redirecting all other requests to index.html');
app.use(history({ verbose: false }));

log('Enabling webpack dev middleware.');
app.use(webpackDevMiddleware(compiler, {
  lazy: false,
  noInfo: false,
  quiet: false,
  stats: config.compiler.stats,
}));

log('Enabling Webpack Hot Module Replacement (HMR).');

// Run Browsersync and use middleware for Hot Module Replacement
browserSync({
  server: {
    baseDir: 'src',

    middleware: [
      webpackDevMiddleware(compiler, {

        // Dev middleware can't access config, so we provide publicPath in rather hack&pray kind of way  ;)

        publicPath: (config.paths.app.publicPath && config.paths.server.publicPath && config.paths.dist.publicPath),

        stats: { colors: true },
        noInfo: true
      }),

      app.use(webpackHotMiddleware(compiler))
    ]
  },

  files: [
    'src/*.html'
  ]
});


log(`Serving static content from ${config.paths.static}`);
app.use(express.static(config.paths.static));


const port = yargs.argv.port || config.server.port;
app.listen(port, config.server.hostname, () => {
  log(`Server is now running at http://${config.server.hostname}:${port}.`);
});

module.exports = app;
```

While this works unfortunately it does mess some of the css, specifically background and the the footer/login menu. In a way I'm actually quite surprised that it worked so well; perhaps you could give me your opinion about this, obviously I'm a big newbie here and I'm yet to grasp the whole thing. But with few pointers I can find my own way!

**Comment by vincemtnz** [comment]
Hi @Bartekus, good point.

To use browser-sync, all you need need is to proxy it to the express server. These two lines are enough to use browserSync: 

``` js
const browserSync = require('browser-sync');
browserSync.init({
  proxy: `${config.server.hostname}:${port}`
});
```

Since the express server is already serving on port 3000 (which is also the browserSync default port), browserSync would start in port 3001 and 3002. My suggestion would be to change the port 4000 for example, and then proxy from browsersync (that way browsersync gets port 3000).

``` js
app.listen(4000, config.server.hostname);
browserSync.init({
  proxy: `${config.server.hostname}:4000`
});
```

**Comment by bartekus** [comment]
Thank you so kindly @eyko ! I'll implement this at once, currently I diverged a little bit and I'm looking at general architecture of the landing page as I attempt to inject another picture in place of the title. I must say I have never been this excited and yet frustrated lol, but I can't walk away from this, you guys simply created marvel here, I've seen and work on other boilerplates, but this one here, it's pure joy! Is immaculate in it's structural composition and pristine in the way how it follows core concepts of react and redux!

**Comment by bartekus** [comment]
The outlined task has been completed and submitted with pull request:
#41 - BrowserSync Integration
