### ISSUE TITLE
Document IDE setup

### ISSUE THREAD

**Issue by mcalthrop** [opencredo/opencredo-react-boilerplate#5]
Start with Intellij/Webstorm, and leave space for others (sublime, Atom).

**Comment by bartekus** [comment]
I'm not sure to what extend this can be done without dirtying the build with .idea folder addition.
I would need a breakdown of what's really needed as I'm not sure atm, but I do have WebStorm, so given specifics I might be able to come up with something. 
Meanwhile I'm attaching few reference which would deal specifically with use of Webstorm and Webpack in area of debugging.
[Debugging Webpack applications in WebStorm](http://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/)
[Debugging WebPack in WebStorm 11](http://stackoverflow.com/questions/32445932/debugging-webpack-in-webstorm-11) 
[debugging-webpack](https://github.com/prigara/debugging-webpack)

**Comment by vincemtnz** [comment]
I'm wondering what the intended scope is. As I have very little experience with JavaScript IDEs, someone other than me is probably better suited to document WebStorm/IntelliJ.

With the exception of WebStorm/IntelliJ, I assume we're documenting a couple of editors: [Atom](http://atom.io/) and [SublimeText 3](https://www.sublimetext.com/3). I've thought about adding Vim to the list but it's unlikely that any Vim users will not already have a preferred list of vim plugins for JavaScript syntax highlighting, code completion, JSX support, etc. 

With that in mind, I'm covering the following points: 
- [ ] **Flowtype**
- [ ] **JSX**
- [ ] ES6
- [ ] eslint 
- [ ] editorconfig support for consistency

In bold are the points that I think are in scope. The rest I think would be out of scope.
