### ISSUE TITLE
Update package dependency versions

### ISSUE THREAD

**Issue by mcalthrop** [opencredo/opencredo-react-boilerplate#73]
Several packages have become out of date... update them.

Also: make sure that the `redux-form-validation` points back to the updated original repo instead of the `@mcalthrop`-namespaced repo.

**Comment by mcalthrop** [comment]
Package dependencies' and devDependencies' versions have been updated, and ESLint errors fixed.

`npm run start` now works, but running the app in the browser generates the following JS console error:

`Uncaught TypeError: (0 , _reactRouterRedux.syncHistory) is not a function`

Guessing this is because of breaking changes in v4.0.0 of `react-router-redux`: https://github.com/reactjs/react-router-redux/blob/master/CHANGELOG.md#400

**Comment by vincemtnz** [comment]
We need to make a separate issue to deal with these:
- Update React Router + Redux usage (possibly deprecate react-router-redux?)
- Update flow-bin once 0.22 JSON bugs are fixed

**Comment by Tux1** [comment]
How did you fix this ?

**Comment by mcalthrop** [comment]
@tux1: which issue are you referring to?

If you mean the JS console error, at the moment we've just left `react-router-redux` at version `^2.1.0`.

There's an outstanding task to [Update React Router + Redux usage](https://github.com/opencredo/opencredo-react-boilerplate/issues/75).
